basePath: /
definitions:
  ds.Meals:
    properties:
      id:
        type: integer
      image_url:
        type: string
      meal_brand:
        type: string
      meal_detail:
        type: string
      meal_info:
        type: string
      meal_weight:
        type: string
      status:
        type: boolean
    type: object
  ds.MilkRequests:
    properties:
      address:
        type: string
      creator:
        $ref: '#/definitions/ds.Users'
      creator_id:
        type: integer
      date_create:
        type: string
      date_finish:
        type: string
      date_update:
        type: string
      delivery_date:
        type: string
      id:
        type: integer
      moderator:
        $ref: '#/definitions/ds.Users'
      moderator_id:
        type: integer
      recipient_name:
        type: string
      recipient_surname:
        type: string
      status:
        type: integer
    type: object
  ds.Users:
    properties:
      id:
        type: integer
      is_moderator:
        type: boolean
      login:
        type: string
      password:
        type: string
    type: object
  schemas.AddMealToMilkReqResponse:
    properties:
      mealID:
        type: integer
      messageResponse:
        type: string
      milkRequestID:
        type: integer
    type: object
  schemas.CreateMealRequest:
    properties:
      image_url:
        type: string
      meal_brand:
        type: string
      meal_detail:
        type: string
      meal_info:
        type: string
      meal_weight:
        type: string
      status:
        type: boolean
    type: object
  schemas.CreateMealResponse:
    properties:
      id:
        type: integer
      messageResponse:
        type: string
    type: object
  schemas.DeleteMealResponse:
    properties:
      id:
        type: integer
      messageResponse:
        type: string
    type: object
  schemas.GetAllMealsResponse:
    properties:
      count:
        type: integer
      meals:
        items:
          $ref: '#/definitions/ds.Meals'
        type: array
      milk_req_ID:
        type: integer
    type: object
  schemas.GetAllMilkRequestsWithParamsResponse:
    properties:
      milkRequests:
        items:
          $ref: '#/definitions/ds.MilkRequests'
        type: array
    type: object
  schemas.GetMealResponse:
    properties:
      meal:
        $ref: '#/definitions/ds.Meals'
    type: object
  schemas.LoginUserRequest:
    properties:
      login:
        type: string
      password:
        type: string
    type: object
  schemas.RegisterUserRequest:
    properties:
      login:
        type: string
      password:
        type: string
    type: object
  schemas.ResponseMessage:
    type: object
  schemas.UpdateMealRequest:
    properties:
      image_url:
        type: string
      meal_brand:
        type: string
      meal_detail:
        type: string
      meal_info:
        type: string
      meal_weight:
        type: string
      status:
        type: boolean
    type: object
  schemas.UpdateMealResponse:
    properties:
      id:
        type: integer
      messageResponse:
        type: string
    type: object
host: localhost:8080
info:
  contact: {}
  description: This is API for Milk Kitchen requests
  title: DevIntApp
  version: "1.1"
paths:
  /api/login_user:
    post:
      consumes:
      - application/json
      description: Authenticates a user and returns a JWT token.
      parameters:
      - description: User login data
        in: body
        name: body
        required: true
        schema:
          $ref: '#/definitions/schemas.LoginUserRequest'
      produces:
      - application/json
      responses:
        "200":
          description: User logged in successfully
          schema:
            $ref: '#/definitions/schemas.ResponseMessage'
        "400":
          description: Invalid request body
          schema:
            $ref: '#/definitions/schemas.ResponseMessage'
        "500":
          description: Internal server error
          schema:
            $ref: '#/definitions/schemas.ResponseMessage'
      summary: Login a user
      tags:
      - users
  /api/logout:
    post:
      consumes:
      - application/json
      description: Log out the user by blacklisting the token
      parameters:
      - description: Bearer Token
        in: header
        name: Authorization
        required: true
        type: string
      - description: User login
        in: header
        name: Login
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: User logged out successfully
          schema:
            $ref: '#/definitions/schemas.ResponseMessage'
        "401":
          description: Missing token
          schema:
            $ref: '#/definitions/schemas.ResponseMessage'
        "500":
          description: Internal server error
          schema:
            $ref: '#/definitions/schemas.ResponseMessage'
      summary: Logout
      tags:
      - users
  /api/meal:
    post:
      consumes:
      - application/json
      description: Create meal with properties
      parameters:
      - description: Meal data
        in: body
        name: body
        required: true
        schema:
          $ref: '#/definitions/schemas.CreateMealRequest'
      produces:
      - application/json
      responses:
        "201":
          description: Created
          schema:
            $ref: '#/definitions/schemas.CreateMealResponse'
        "400":
          description: Invalid request body
          schema:
            $ref: '#/definitions/schemas.ResponseMessage'
        "500":
          description: Internal server error
          schema:
            $ref: '#/definitions/schemas.ResponseMessage'
      summary: Create meal
      tags:
      - meals
  /api/meal/{ID}:
    delete:
      consumes:
      - application/json
      description: Delete meal using its ID
      parameters:
      - description: Meal ID
        in: path
        name: ID
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/schemas.DeleteMealResponse'
        "400":
          description: Invalid request body
          schema:
            $ref: '#/definitions/schemas.ResponseMessage'
        "500":
          description: Internal server error
          schema:
            $ref: '#/definitions/schemas.ResponseMessage'
      summary: Delete meal by ID
      tags:
      - meals
    get:
      consumes:
      - application/json
      description: Get info about meal using its ID
      parameters:
      - description: Meal ID
        in: path
        name: ID
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/schemas.GetMealResponse'
        "400":
          description: Invalid request body
          schema:
            $ref: '#/definitions/schemas.ResponseMessage'
        "500":
          description: Internal server error
          schema:
            $ref: '#/definitions/schemas.ResponseMessage'
      summary: Get meal by ID
      tags:
      - meals
    put:
      consumes:
      - application/json
      description: Update meal using its ID with parametres
      parameters:
      - description: Meal ID
        in: path
        name: ID
        required: true
        type: string
      - description: Update meal data
        in: body
        name: body
        required: true
        schema:
          $ref: '#/definitions/schemas.UpdateMealRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/schemas.UpdateMealResponse'
        "400":
          description: Invalid request body
          schema:
            $ref: '#/definitions/schemas.ResponseMessage'
        "500":
          description: Internal server error
          schema:
            $ref: '#/definitions/schemas.ResponseMessage'
      summary: Update meal by ID
      tags:
      - meals
  /api/meal/change_pic/{ID}:
    post:
      consumes:
      - application/json
      description: This endpoint allows you to add a meal to a milk request by its
        ID.
      parameters:
      - description: Meal ID
        in: path
        name: ID
        required: true
        type: string
      - description: Изображение получателя
        in: formData
        name: image
        required: true
        type: file
      produces:
      - application/json
      responses:
        "200":
          description: Changed
          schema:
            $ref: '#/definitions/schemas.ResponseMessage'
      summary: Add Meal to Milk Request
      tags:
      - meals
  /api/meal_to_milk_request/{ID}:
    post:
      consumes:
      - application/json
      description: This endpoint allows you to add a meal to a milk request by its
        ID.
      parameters:
      - description: Meal ID
        in: path
        name: ID
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: Meal added successfully
          schema:
            $ref: '#/definitions/schemas.AddMealToMilkReqResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/schemas.ResponseMessage'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/schemas.ResponseMessage'
      summary: Add Meal to Milk Request
      tags:
      - meals
  /api/meals:
    get:
      consumes:
      - application/json
      description: Returns a list ofall meals.
      produces:
      - application/json
      responses:
        "200":
          description: List of meals retrieved successfully
          schema:
            $ref: '#/definitions/schemas.GetAllMealsResponse'
        "400":
          description: Invalid request body
          schema:
            $ref: '#/definitions/schemas.ResponseMessage'
        "500":
          description: Internal server error
          schema:
            $ref: '#/definitions/schemas.ResponseMessage'
      summary: Get all meals
      tags:
      - meals
  /api/milk_requests:
    get:
      consumes:
      - application/json
      description: Получить список запросов на молоко с возможностью фильтрации по
        статусу и датам
      parameters:
      - description: Статус заявки
        in: query
        name: status
        type: string
      - description: Наличие статуса
        in: query
        name: is_status
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/schemas.GetAllMilkRequestsWithParamsResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/schemas.ResponseMessage'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/schemas.ResponseMessage'
      security:
      - BearerAuth: []
      summary: Получить все заявки на молочную кухню с параметрами
      tags:
      - milk_requests
  /api/register_user:
    post:
      consumes:
      - application/json
      description: Registers a new user.
      parameters:
      - description: User registration data
        in: body
        name: body
        required: true
        schema:
          $ref: '#/definitions/schemas.RegisterUserRequest'
      produces:
      - application/json
      responses:
        "200":
          description: User registered successfully
          schema:
            $ref: '#/definitions/schemas.ResponseMessage'
        "400":
          description: Invalid request body
          schema:
            $ref: '#/definitions/schemas.ResponseMessage'
        "409":
          description: User with this login already exists
          schema:
            $ref: '#/definitions/schemas.ResponseMessage'
        "500":
          description: Internal server error
          schema:
            $ref: '#/definitions/schemas.ResponseMessage'
      summary: Register a new user
      tags:
      - users
  /milk_req_meals/{ID}:
    delete:
      consumes:
      - application/json
      description: Удаляет блюдо из запроса на молоко по ID запроса и MealID
      parameters:
      - description: ID запроса на молоко
        in: path
        name: ID
        required: true
        type: string
      - description: ID блюда
        in: query
        name: MealID
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: Meal was deleted from milk request
          schema:
            type: string
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/schemas.ResponseMessage'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/schemas.ResponseMessage'
      summary: Удалить блюдо из запроса на молоко
      tags:
      - meals_and_requests
securityDefinitions:
  BearerAuth:
    in: header
    name: Authorization
    type: apiKey
swagger: "2.0"
